/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeManagement;

import CustomerManagement.Customermain;
import FinancialHandling.FinancialHandling;
import Sales.Salesmain;
import SectionManagement.MainpageSection;
import StockManagement.StockMain;
import SupplierManagement.SupplierMain;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author pc
 */
public class Login extends javax.swing.JFrame {
    
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Home
     */
    public Login() {
        initComponents();
        conn = db.java_db();
        //Set Full Screen
        Toolkit tk = Toolkit.getDefaultToolkit();

        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();

        this.setSize(xsize, ysize);
        //Set Full FullScreen End
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        combo_category = new javax.swing.JComboBox<>();
        jToggleButton9 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1069, 830));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Select category :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 430, 210, 80);

        jLabel4.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("Username : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 280, 140, 80);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 350, 140, 80);

        txt_username.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        getContentPane().add(txt_username);
        txt_username.setBounds(670, 300, 180, 40);

        txt_password.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        getContentPane().add(txt_password);
        txt_password.setBounds(670, 370, 180, 40);

        combo_category.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        combo_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Sales", "Section Manager", "Stock Manager", "Financial Handling", "Supplier Manager", "Customer Manager" }));
        getContentPane().add(combo_category);
        combo_category.setBounds(670, 440, 300, 40);

        jToggleButton9.setBackground(new java.awt.Color(85, 55, 118));
        jToggleButton9.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Picture4n.png"))); // NOI18N
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton9);
        jToggleButton9.setBounds(930, 40, 270, 200);

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 530, 110, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Symbol", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 153));
        jLabel5.setText("LOGIN TO GUNASIRI ENTERPRISES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 70, 550, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/purple-pink-wallpapers-25280-7704742.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 2560, 1600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username=txt_username.getText();
        String password=txt_password.getText();
        String category=combo_category.getSelectedItem().toString();
        
        try{
            int log=1;
            String sql2="Select * from login";
            pst=conn.prepareStatement(sql2);
            rs=pst.executeQuery();
            
            while(rs.next()){
                if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Manager")){
                    log=0;
                    break;
                }
                
                 if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Section Manager")){
                    log=1;
                    break;
                }
                 
                 if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Supplier Manager")){
                    log=2;
                    break;
                }
                 
                 if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Financial Handling")){
                    log=3;
                    break;
                }
                 
                 if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Customer Manager")){
                    log=4;
                    break;
                }
                 
                 if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Sales")){
                    log=5;
                    break;
                }
                 
                 if(rs.getString(2).equals(username) && rs.getString(3).equals(password) &&  rs.getString(4).equalsIgnoreCase("Stock Manager")){
                    log=6;
                    break;
                }
            }
            if(log==0){
                
                Employeemain samp=new Employeemain();
                samp.setVisible(true);
                setVisible(false);
            }
            
            else if(log==1){
                
                MainpageSection samp1=new MainpageSection();
                samp1.setVisible(true);
                setVisible(false);
            }
            
            else if(log==2){
                
                SupplierMain samp2=new SupplierMain();
                samp2.setVisible(true);
                setVisible(false);
            }
            
            else if(log==3){
                
                FinancialHandling samp3=new FinancialHandling();
                samp3.setVisible(true);
                setVisible(false);
            }
            
            else if(log==4){
                
                Customermain samp4=new Customermain();
                samp4.setVisible(true);
                setVisible(false);
            }
            
            else if(log==5){
                
                Salesmain samp5=new Salesmain();
                samp5.setVisible(true);
                setVisible(false);
            }
            
             else if(log==6){
                
                StockMain samp6=new StockMain();
                samp6.setVisible(true);
                setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Username or password is incorrect");
                txt_username.setText(" ");
                txt_password.setText(" ");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_category;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
